import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';

/**
 * The dates the e2e run is built around, decided ONCE and written down.
 *
 * Every process in a Playwright run used to call `todayInMuscat()` for itself —
 * globalSetup to choose what to seed, each spec to decide where to navigate.
 * That is three independent readings of a clock that moves. A run starting
 * before Muscat midnight and continuing after it would have globalSetup seed
 * for day D while a spec expected the board to read D, and a spec computing a
 * NEGATIVE offset from its own later `today` could ask for a reference date two
 * days old — which migration 0005 refuses outright. Neither failure involves a
 * defect in the application.
 *
 * So the anchor is resolved once, persisted, and read by everyone else. The
 * clock can advance mid-run; the targets cannot.
 *
 * Every target is at least two days in the FUTURE. No spec ever seeds a past
 * date, and navigation is always forwards from whatever the board reports —
 * computed from the board's ACTUAL label, never from a remembered "today".
 */
export interface SeedContext {
  /** Muscat date at the moment globalSetup ran. Recorded for diagnosis; specs
   * must not navigate from it — the board's own label is the truth. */
  resolvedAt: string;
  /** What globalSetup actually seeded, so the base spec knows what to expect. */
  baseReference: string;
  /** A future Thursday, Friday (the day off) and Saturday from one week. */
  thursday: string;
  dayOff: string;
  saturday: string;
  /** A future month boundary and the side of it that has bookings. */
  monthEnd: string;
  nextMonthStart: string;
  monthBoundaryTarget: string;
}

/** Test output, not tracked state: regenerated by every run, gitignored. */
export const SEED_CONTEXT_PATH = resolve(process.cwd(), 'test-results/e2e-seed-context.json');

export function writeSeedContext(context: SeedContext): void {
  mkdirSync(dirname(SEED_CONTEXT_PATH), { recursive: true });
  writeFileSync(SEED_CONTEXT_PATH, JSON.stringify(context, null, 2));
}

export function readSeedContext(): SeedContext {
  try {
    return JSON.parse(readFileSync(SEED_CONTEXT_PATH, 'utf8')) as SeedContext;
  } catch (error) {
    throw new Error(
      `No e2e seed context at ${SEED_CONTEXT_PATH}. globalSetup writes it; a spec must ` +
        `never recompute the reference date for itself. (${(error as Error).message})`,
    );
  }
}

/** Whole days from `from` to `to`, both Muscat calendar dates. */
export function daysBetween(from: string, to: string): number {
  const a = Date.parse(`${from}T00:00:00Z`);
  const b = Date.parse(`${to}T00:00:00Z`);
  return Math.round((b - a) / 86_400_000);
}
